config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  resources :bookmarks
  resources :documents
  resources :sessions
  resources :users

  match '/login', to: 'sessions#new', via: 'get'
  match '/logout', to: 'sessions#destroy', via: 'post'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :document
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :user
  has_many :bookmark
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  before_save { email.downcase! }

  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :password,
            confirmation: true,
            length: { minimum: 8 },
            if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation,
            presence: true,
            if: -> { new_record? || changes[:crypted_password] }

  has_many :document
  has_many :bookmark
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: [:show, :edit, :update, :destroy]

  # GET /bookmarks
  # GET /bookmarks.json
  def index
    @bookmarks = Bookmark.all
  end

  # GET /bookmarks/1
  # GET /bookmarks/1.json
  def show
  end

  # GET /bookmarks/new
  def new
    @bookmark = Bookmark.new
  end

  # GET /bookmarks/1/edit
  def edit
  end

  # POST /bookmarks
  # POST /bookmarks.json
  def create
    @bookmark = Bookmark.new(bookmark_params)

    respond_to do |format|
      if @bookmark.save
        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully created.' }
        format.json { render :show, status: :created, location: @bookmark }
      else
        format.html { render :new }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookmarks/1
  # PATCH/PUT /bookmarks/1.json
  def update
    respond_to do |format|
      if @bookmark.update(bookmark_params)
        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully updated.' }
        format.json { render :show, status: :ok, location: @bookmark }
      else
        format.html { render :edit }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookmarks/1
  # DELETE /bookmarks/1.json
  def destroy
    @bookmark.destroy
    respond_to do |format|
      format.html { redirect_to bookmarks_url, notice: 'Bookmark was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bookmark
      @bookmark = Bookmark.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bookmark_params
      params.require(:bookmark).permit(:type, :client, :position, :note, :user_id, :document_id)
    end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]

  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:name, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to(:users, success: 'Login successful')
    else
      flash.now[:warning] = 'Invalid email/password combination'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(login_path, success: 'Logged out!')
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def contact
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def application_name
    'Sample App'
  end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookmarks/_form.html.slim
= form_for(bookmark) do |f|
  - if bookmark.errors.any?
    #error_explanation
      h2
        = pluralize(bookmark.errors.count, "error")
        |  prohibited this bookmark from being saved:
      ul
        - bookmark.errors.full_messages.each do |message|
          li
            = message
  .field
    = f.label :type
    = f.text_field :type
  .field
    = f.label :client
    = f.text_field :client
  .field
    = f.label :position
    = f.text_field :position
  .field
    = f.label :note
    = f.text_field :note
  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :document_id
    = f.number_field :document_id
  .actions
    = f.submit

app/views/bookmarks/edit.html.slim
h1
  | Editing Bookmark
= render 'form', bookmark: @bookmark
= link_to 'Show', @bookmark
|  | 
= link_to 'Back', bookmarks_path

app/views/bookmarks/index.html.slim
p#notice
  = notice
h1
  | Bookmarks
table
  thead
    tr
      th
        | Type
      th
        | Client
      th
        | Position
      th
        | Note
      th
        | User
      th
        | Document
      th[colspan="3"]
  tbody
    - @bookmarks.each do |bookmark|
      tr
        td
          = bookmark.type
        td
          = bookmark.client
        td
          = bookmark.position
        td
          = bookmark.note
        td
          = bookmark.user_id
        td
          = bookmark.document_id
        td
          = link_to 'Show', bookmark
        td
          = link_to 'Edit', edit_bookmark_path(bookmark)
        td
          = link_to 'Destroy', bookmark, method: :delete, data: { confirm: 'Are you sure?' }
br
= link_to 'New Bookmark', new_bookmark_path

app/views/bookmarks/new.html.slim
h1
  | New Bookmark
= render 'form', bookmark: @bookmark
= link_to 'Back', bookmarks_path

app/views/bookmarks/show.html.slim
p#notice
  = notice
p
  strong
    | Type:
  = @bookmark.type
p
  strong
    | Client:
  = @bookmark.client
p
  strong
    | Position:
  = @bookmark.position
p
  strong
    | Note:
  = @bookmark.note
p
  strong
    | User:
  = @bookmark.user_id
p
  strong
    | Document:
  = @bookmark.document_id
= link_to 'Edit', edit_bookmark_path(@bookmark)
|  | 
= link_to 'Back', bookmarks_path

app/views/documents/_form.html.slim
= form_for(document) do |f|
  - if document.errors.any?
    #error_explanation
      h2
        = pluralize(document.errors.count, "error")
        |  prohibited this document from being saved:
      ul
        - document.errors.full_messages.each do |message|
          li
            = message
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :user_id
    = f.number_field :user_id
  .actions
    = f.submit

app/views/documents/edit.html.slim
h1
  | Editing Document
= render 'form', document: @document
= link_to 'Show', @document
|  | 
= link_to 'Back', documents_path

app/views/documents/index.html.slim
p#notice
  = notice
h1
  | Documents
table
  thead
    tr
      th
        | Name
      th
        | User
      th[colspan="3"]
  tbody
    - @documents.each do |document|
      tr
        td
          = document.name
        td
          = document.user_id
        td
          = link_to 'Show', document
        td
          = link_to 'Edit', edit_document_path(document)
        td
          = link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' }
br
= link_to 'New Document', new_document_path

app/views/documents/new.html.slim
h1
  | New Document
= render 'form', document: @document
= link_to 'Back', documents_path

app/views/documents/show.html.slim
p#notice
  = notice
p
  strong
    | Name:
  = @document.name
p
  strong
    | User:
  = @document.user_id
= link_to 'Edit', edit_document_path(@document)
|  | 
= link_to 'Back', documents_path

app/views/layouts/_footer.html.slim
footer.footer
  small
    = application_name
  nav
    ul
      li = link_to "About", about_path
      li = link_to "Contact", contact_path
      li
        a href="http://news.railstutorial.jp" News

app/views/layouts/_header.html.slim
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      = link_to application_name, '#', id: 'logo', class: 'navbar-brand'
    .navbar-collapse.collapse
      ul.nav.navbar-nav.pull-right
        li = link_to "Help", help_path
        - if current_user
          li = link_to "Logout", logout_path, method: :post
        - else
          li = link_to "Sign in", login_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title = application_name
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    == render 'layouts/header'
    .container
      - flash.each do |k, v|
        div class="alert alert-#{k}"
          = v
      == yield
      = render 'layouts/footer'

app/views/static_pages/about.html.slim
h1 StaticPages#about
p Find me in app/views/static_pages/about.html.slim

app/views/static_pages/contact.html.slim
= provide :title, 'Contact'
h1 Contact
p
  | Contact Ruby on Rails Tutorial about the sample app at the
  a href="http://railstutorial.jp/contact" contact page

app/views/static_pages/help.html.slim
h1 StaticPages#help
p Find me in app/views/static_pages/help.html.slim

app/views/static_pages/home.html.slim
.center.jumbotron
  h1 Welcome to the Sample App
  h2
    | This is the home page for the
    a<> href="http://raisltutorial.jp/" Ruby on Rails Tutorial
    | sample application.
  = link_to "Sign up now!", "#", class: "btn btn-large btn-primary"
= link_to image_tag('rails.png', alt: 'Rails'), 'http://rubyonrails.org/'

app/views/users/_form.html.slim
= form_for(user) do |f|
  - if user.errors.any?
    #error_explanation
      h2
        = pluralize(user.errors.count, "error")
        |  prohibited this user from being saved:
      ul
        - user.errors.full_messages.each do |message|
          li
            = message
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :password
    = f.password_field :password
  .field
    = f.label :password_confirmation
    = f.password_field :password_confirmation
  .actions
    = f.submit

app/views/users/edit.html.slim
h1
  | Editing User
= render 'form', user: @user
= link_to 'Show', @user
|  | 
= link_to 'Back', users_path

app/views/users/index.html.slim
p#notice
  = notice
h1
  | Users
table
  thead
    tr
      th
        | Email
      th[colspan="3"]
  tbody
    - @users.each do |user|
      tr
        td
          = user.email
        td
          = link_to 'Show', user
        td
          = link_to 'Edit', edit_user_path(user)
        td
          = link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }
br
= link_to 'New User', new_user_path

app/views/users/new.html.slim
h1
  | New User
= render 'form', user: @user
= link_to 'Back', users_path

app/views/users/show.html.slim
p#notice
  = notice
p
  strong
    | Email:
  = @user.email
= link_to 'Edit', edit_user_path(@user)
|  | 
= link_to 'Back', users_path